//==========================================================================
// This file was automatically generated by HReader.GenerateStorageQueries
//==========================================================================
using System;

namespace HReader.Core.Storage.Queries
{
    internal partial class QueryManager
    {
        private readonly Lazy<string> schema = ReadLazy("Schema.sql");
        private readonly Lazy<string> deleteEntries = ReadLazy("Delete.Entries.sql");
        private readonly Lazy<string> deleteEntry = ReadLazy("Delete.Entry.sql");
        private readonly Lazy<string> insertArtist = ReadLazy("Insert.Artist.sql");
        private readonly Lazy<string> insertArtistEntry = ReadLazy("Insert.ArtistEntry.sql");
        private readonly Lazy<string> insertCharacter = ReadLazy("Insert.Character.sql");
        private readonly Lazy<string> insertCharacterEntry = ReadLazy("Insert.CharacterEntry.sql");
        private readonly Lazy<string> insertEntry = ReadLazy("Insert.Entry.sql");
        private readonly Lazy<string> insertPage = ReadLazy("Insert.Page.sql");
        private readonly Lazy<string> insertSeries = ReadLazy("Insert.Series.sql");
        private readonly Lazy<string> insertSeriesEntry = ReadLazy("Insert.SeriesEntry.sql");
        private readonly Lazy<string> insertTag = ReadLazy("Insert.Tag.sql");
        private readonly Lazy<string> insertTagEntry = ReadLazy("Insert.TagEntry.sql");
        private readonly Lazy<string> selectEntryArtists = ReadLazy("Select.EntryArtists.sql");
        private readonly Lazy<string> selectEntryCharacters = ReadLazy("Select.EntryCharacters.sql");
        private readonly Lazy<string> selectEntryCount = ReadLazy("Select.EntryCount.sql");
        private readonly Lazy<string> selectEntryPage = ReadLazy("Select.EntryPage.sql");
        private readonly Lazy<string> selectEntryPages = ReadLazy("Select.EntryPages.sql");
        private readonly Lazy<string> selectEntrySeries = ReadLazy("Select.EntrySeries.sql");
        private readonly Lazy<string> selectEntryTags = ReadLazy("Select.EntryTags.sql");

        public string Schema => schema.Value;
        public string DeleteEntries => deleteEntries.Value;
        public string DeleteEntry => deleteEntry.Value;
        public string InsertArtist => insertArtist.Value;
        public string InsertArtistEntry => insertArtistEntry.Value;
        public string InsertCharacter => insertCharacter.Value;
        public string InsertCharacterEntry => insertCharacterEntry.Value;
        public string InsertEntry => insertEntry.Value;
        public string InsertPage => insertPage.Value;
        public string InsertSeries => insertSeries.Value;
        public string InsertSeriesEntry => insertSeriesEntry.Value;
        public string InsertTag => insertTag.Value;
        public string InsertTagEntry => insertTagEntry.Value;
        public string SelectEntryArtists => selectEntryArtists.Value;
        public string SelectEntryCharacters => selectEntryCharacters.Value;
        public string SelectEntryCount => selectEntryCount.Value;
        public string SelectEntryPage => selectEntryPage.Value;
        public string SelectEntryPages => selectEntryPages.Value;
        public string SelectEntrySeries => selectEntrySeries.Value;
        public string SelectEntryTags => selectEntryTags.Value;
    }
}